name: ai-os
base: core22
adopt-info: ai-os
summary: Autonomous HRM agent with CLI and GUI interfaces
description: |
  AI-OS provides command-line and graphical workflows for managing autonomous
  HRM agents, packaging the project with its default artifacts and configuration.
grade: devel
confinement: classic
icon: ../../AI-OS.png

apps:
  aios:
    command: bin/aios
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - audio-playback
      - pulseaudio
      - opengl
  aios-gui:
    command: bin/aios gui
    desktop: meta/gui/ai-os.desktop
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - audio-playback
      - pulseaudio
      - opengl
      - browser-support

parts:
  ai-os:
    plugin: nil
    source: ../../..
    source-type: local
    build-packages:
      - build-essential
      - python3-dev
      - python3-venv
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - pkg-config
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libjpeg-dev
      - libpng-dev
      - rsync
    stage-packages:
      - python3
      - python3-venv
      - python3-minimal
      - python3-tk
      - libgdk-pixbuf-2.0-0
      - libgtk-3-0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libnss3
      - libasound2
      - libpulse0
      - libdrm2
      - libgbm1
      - libgl1
      - libglu1-mesa
      - libgles2
      - libegl1
      - libopengl0
      - libx11-6
      - libxext6
      - libxrandr2
      - libxrender1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxi6
      - libxtst6
      - libxkbcommon0
      - libsm6
      - libice6
      - libsndfile1
      - ffmpeg
      - libsecret-1-0
      - libayatana-appindicator3-1
      - xdg-utils
      - ca-certificates
      - fonts-dejavu-core
    override-build: |
      set -eu
      version="$(python3 - <<'PY'
      import os
      import pathlib

      project_root = pathlib.Path(os.environ["CRAFT_PART_SRC"])
      version = None
      in_project = False
      for raw in (project_root / "pyproject.toml").read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("["):
          in_project = (line == "[project]")
        elif in_project and line.startswith("version"):
          _, value = line.split("=", 1)
          version = value.strip().strip('"').strip("'")
          break
      if not version:
        raise SystemExit("Unable to determine version from pyproject.toml")
      print(version)
      PY
      )"
      craftctl set version="$version"

      install_root="$CRAFT_PART_INSTALL/opt/ai-os"
      mkdir -p "$install_root"
      rsync -a --delete \
        --exclude='.git' \
        --exclude='.mypy_cache' \
        --exclude='.ruff_cache' \
        --exclude='__pycache__' \
        --exclude='.venv' \
        --exclude='logs' \
        --exclude='installers/_builds' \
        --exclude='installers/releases' \
        "$CRAFT_PART_SRC"/ "$install_root"/

      if [ ! -d "$install_root/src" ]; then
        echo "Project copy is missing src/ directory" >&2
        exit 1
      fi

      python3 -m venv --copies "$install_root/venv"
      "$install_root/venv/bin/python" -m pip install --upgrade pip setuptools wheel
      old_pwd=$(pwd)
      cd "$install_root"
      PIP_NO_CACHE_DIR=1 "$install_root/venv/bin/pip" install ".[ui]"
      cd "$old_pwd"

      mkdir -p "$CRAFT_PART_INSTALL/bin"
      cat <<'EOF' >"$CRAFT_PART_INSTALL/bin/aios"
      #!/usr/bin/env bash
      set -euo pipefail
      APP_ROOT="$SNAP/opt/ai-os"
      VENV="$APP_ROOT/venv"
      if [[ ! -x "$VENV/bin/python" ]]; then
        echo "AI-OS virtual environment missing. Please reinstall the ai-os snap." >&2
        exit 1
      fi
      export PYTHONPATH="$APP_ROOT/src${PYTHONPATH:+:$PYTHONPATH}"
      export AIOS_HF_CACHE="${AIOS_HF_CACHE:-$SNAP_COMMON/hf_cache}"
      export HF_HOME="$AIOS_HF_CACHE"
      export HF_DATASETS_CACHE="$AIOS_HF_CACHE/datasets"
      export HF_HUB_CACHE="$AIOS_HF_CACHE/hub"
      export PLAYWRIGHT_BROWSERS_PATH="${PLAYWRIGHT_BROWSERS_PATH:-$SNAP_COMMON/playwright}"
      export AIOS_DATA_HOME="${AIOS_DATA_HOME:-$SNAP_COMMON}"
      export AIOS_ARTIFACTS_DIR="${AIOS_ARTIFACTS_DIR:-$SNAP_COMMON/artifacts}"
      mkdir -p "$AIOS_HF_CACHE" "$HF_DATASETS_CACHE" "$HF_HUB_CACHE" "$PLAYWRIGHT_BROWSERS_PATH" "$AIOS_ARTIFACTS_DIR"
      cd "$APP_ROOT"
      exec "$VENV/bin/python" -m aios.cli.aios "$@"
      EOF
      chmod 755 "$CRAFT_PART_INSTALL/bin/aios"

      cat <<'EOF' >"$CRAFT_PART_INSTALL/bin/aios-gui"
      #!/usr/bin/env bash
      set -euo pipefail
      exec "$SNAP/bin/aios" gui "$@"
      EOF
      chmod 755 "$CRAFT_PART_INSTALL/bin/aios-gui"

      icon_source=""
      if [ -f "$install_root/installers/AI-OS.png" ]; then
        icon_source="$install_root/installers/AI-OS.png"
      elif [ -f "$CRAFT_PART_SRC/installers/AI-OS.png" ]; then
        icon_source="$CRAFT_PART_SRC/installers/AI-OS.png"
      elif [ -f "$CRAFT_PART_SRC/AI-OS.png" ]; then
        icon_source="$CRAFT_PART_SRC/AI-OS.png"
      fi
      if [ -n "$icon_source" ]; then
        install -Dm644 "$icon_source" "$CRAFT_PART_INSTALL/meta/gui/ai-os.png"
      else
        echo "Warning: AI-OS icon not found; snap will use default icon" >&2
      fi

      desktop_source=""
      if [ -f "$CRAFT_PART_SRC/snap/gui/ai-os.desktop" ]; then
        desktop_source="$CRAFT_PART_SRC/snap/gui/ai-os.desktop"
      elif [ -f "$install_root/snap/gui/ai-os.desktop" ]; then
        desktop_source="$install_root/snap/gui/ai-os.desktop"
      fi
      if [ -n "$desktop_source" ]; then
        install -Dm644 "$desktop_source" "$CRAFT_PART_INSTALL/meta/gui/ai-os.desktop"
      else
        echo "Warning: Desktop entry not found; GUI launcher will be missing" >&2
      fi
