#!/usr/bin/env bash
set -euo pipefail

log_info() { printf '[i] %s\n' "$*"; }
log_warn() { printf '[w] %s\n' "$*" >&2; }
log_error() { printf '[!] %s\n' "$*" >&2; }
die() { log_error "$1"; exit 1; }

usage() {
  cat <<'EOF'
Usage: update_apt_repo.sh [options]

Options:
  --deb <path>             Path to .deb to publish (defaults to newest in installers/releases)
  --repo-dir <path>        Root directory of the apt repo (default: installers/releases/apt)
  --dist <name>            Distribution codename/suite for apt repo (default: stable)
  --component <name>       Repository component (default: main)
  --gpg-key <key-id>       Override default GPG key (defaults to AI-OS release key)
  --no-sign                Skip signing Release files
  --build-source           Force creation of a Debian source package
  --ppa <ppa:name>         Launchpad PPA target for dput (implies --build-source)
  --ppa-dist <codename>    Ubuntu series used in the generated changelog (default: noble)
  --ppa-revision <rev>     Debian revision suffix without leading hyphen (default: 0ppa1)
  --changes <path>         Source .changes file to upload with dput (optional when --ppa builds one)
  --force                  Skip confirmation prompts
  --help                   Show this help message
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if command -v git >/dev/null 2>&1 && git -C "$SCRIPT_DIR" rev-parse --show-toplevel >/dev/null 2>&1; then
  REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
else
  REPO_ROOT="$(realpath "$SCRIPT_DIR/../../..")"
fi
DEFAULT_RELEASE_DIR="$REPO_ROOT/installers/releases"
DEFAULT_REPO_DIR="$DEFAULT_RELEASE_DIR/apt"
DEFAULT_GPG_KEY="D30BDDC813C627F5F259FA33328243A210E7BAD4"
DIST="stable"
COMPONENT="main"
DEB_PATH=""
REPO_DIR="$DEFAULT_REPO_DIR"
PPA_TARGET=""
PPA_DIST="noble"
PPA_REVISION="0ppa1"
BUILD_SOURCE="false"
CHANGES_FILE=""
CHANGES_FROM_FLAG="false"
GPG_KEY="$DEFAULT_GPG_KEY"
FORCE="false"

APT_UPDATED="false"
APT_GET="${APT_GET:-$(command -v apt-get || true)}"
SUDO_BIN="${SUDO:-$(command -v sudo || true)}"

ensure_packages() {
  local missing=()
  for pkg in "$@"; do
    dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
  done
  if (( ${#missing[@]} == 0 )); then
    return
  fi
  [[ -n "$APT_GET" ]] || die "apt-get not available; please install: ${missing[*]}"
  local -a prefix=()
  if [[ $EUID -ne 0 ]]; then
    [[ -n "$SUDO_BIN" ]] || die "sudo is required to install packages (${missing[*]})"
    prefix+=("$SUDO_BIN")
  fi
  if [[ "$APT_UPDATED" == "false" ]]; then
    log_info "Updating apt package index..."
    "${prefix[@]}" apt-get update
    APT_UPDATED="true"
  fi
  log_info "Installing missing packages: ${missing[*]}"
  "${prefix[@]}" apt-get install -y "${missing[@]}"
}

write_debian_metadata() {
  local target_dir="$1/debian"
  local series="$2"
  local version_with_rev="$3"
  mkdir -p "$target_dir/source"
  cat >"$target_dir/changelog" <<EOF
ai-os ($version_with_rev) $series; urgency=medium

  * Automated packaging generated by update_apt_repo.sh

 -- Wulfic <support@ai-os.invalid>  $(date -R)
EOF
  cat >"$target_dir/control" <<'EOF'
Source: ai-os
Section: utils
Priority: optional
Maintainer: Wulfic <support@ai-os.invalid>
Build-Depends: debhelper-compat (= 13), python3, python3-venv, python3-pip, python3-setuptools,
 python3-wheel, git, rsync, tar
Standards-Version: 4.6.0
Homepage: https://github.com/Wulfic/AI-OS
Rules-Requires-Root: no

Package: ai-os
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}, python3 (>= 3.10), python3-venv, python3-pip,
 python3-tk, libgdk-pixbuf2.0-0, libgl1, libsndfile1, ffmpeg
Description: AI-OS human resource manager agent with GUI and CLI interfaces
 Future-facing architecture for OS-integrated autonomous assistance.
EOF
  cat >"$target_dir/rules" <<'EOF'
#!/usr/bin/make -f
export DH_VERBOSE=1

%:
__TAB__dh $@

override_dh_auto_configure:
__TAB__true

override_dh_auto_build:
__TAB__true

override_dh_auto_test:
__TAB__true

override_dh_auto_install:
__TAB__set -e; \
__TAB__chmod +x installers/_builds/ubuntu/build_deb.sh; \
__TAB__upstream_version="$(dpkg-parsechangelog -SVersion | sed 's/-[^-]*$//')"; \
__TAB__installers/_builds/ubuntu/build_deb.sh --keep-build --version "$$upstream_version"; \
__TAB__mkdir -p debian/ai-os; \
__TAB__dpkg-deb -x installers/releases/ai-os_$$upstream_version_$(DEB_HOST_ARCH).deb debian/ai-os

override_dh_auto_clean:
__TAB__rm -rf installers/_builds/ubuntu/.deb-build
__TAB__rm -rf installers/releases
EOF
  perl -0pi -e 's/__TAB__/\t/g' "$target_dir/rules"
  chmod 755 "$target_dir/rules"
  cat >"$target_dir/debhelper-compat" <<'EOF'
13
EOF
  cat >"$target_dir/source/format" <<'EOF'
3.0 (quilt)
EOF
  cat >"$target_dir/clean" <<'EOF'
installers/_builds/ubuntu/.deb-build
installers/releases
EOF
}

build_source_package() {
  local upstream_version="$1"
  local revision="$2"
  local series="$3"
  ensure_packages dpkg-dev debhelper devscripts build-essential fakeroot rsync xz-utils tar
  local build_root="$SCRIPT_DIR/.src-build"
  local src_dir="$build_root/ai-os-$upstream_version"
  rm -rf "$build_root"
  mkdir -p "$build_root"
  local orig_tar="$build_root/ai-os_${upstream_version}.orig.tar.gz"
  local release_orig="$DEFAULT_RELEASE_DIR/ai-os_${upstream_version}.orig.tar.gz"
  if [[ -f "$release_orig" ]]; then
    log_info "Reusing existing orig tarball $release_orig"
    tar -C "$build_root" -xzf "$release_orig"
    cp "$release_orig" "$orig_tar"
  else
    mkdir -p "$src_dir"
    rsync -a --delete \
      --exclude='.git' \
      --exclude='installers/releases' \
      --exclude='installers/_builds/ubuntu/.deb-build' \
      --exclude='.venv' \
      "$REPO_ROOT"/ "$src_dir"/
    tar -C "$build_root" \
      --exclude "ai-os-$upstream_version/debian" \
      -czf "$orig_tar" \
      "ai-os-$upstream_version"
  fi
  write_debian_metadata "$src_dir" "$series" "${upstream_version}-${revision}"
  pushd "$src_dir" >/dev/null
  dpkg-buildpackage -S -sa -us -uc
  popd >/dev/null
  local changes="ai-os_${upstream_version}-${revision}_source.changes"
  for artifact in \
    "$changes" \
    "ai-os_${upstream_version}-${revision}.dsc" \
    "ai-os_${upstream_version}-${revision}_source.buildinfo" \
    "ai-os_${upstream_version}.orig.tar.gz" \
    "ai-os_${upstream_version}-${revision}.debian.tar.xz"; do
    mv "$build_root/$artifact" "$DEFAULT_RELEASE_DIR/$artifact"
  done
  CHANGES_FILE="${CHANGES_FILE:-$DEFAULT_RELEASE_DIR/$changes}"
  log_info "Created source package artifacts under $DEFAULT_RELEASE_DIR"
}

sign_changes_file() {
  if [[ -z "$CHANGES_FILE" || -z "$GPG_KEY" ]]; then
    return
  fi
  [[ -f "$CHANGES_FILE" ]] || die "Cannot sign missing changes file: $CHANGES_FILE"
  log_info "Signing $CHANGES_FILE with key $GPG_KEY"
  debsign -k "$GPG_KEY" "$CHANGES_FILE"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deb)
      [[ $# -ge 2 ]] || die "--deb requires a value"
      DEB_PATH="$2"
      shift 2
      ;;
    --repo-dir)
      [[ $# -ge 2 ]] || die "--repo-dir requires a value"
      REPO_DIR="$2"
      shift 2
      ;;
    --dist)
      [[ $# -ge 2 ]] || die "--dist requires a value"
      DIST="$2"
      shift 2
      ;;
    --component)
      [[ $# -ge 2 ]] || die "--component requires a value"
      COMPONENT="$2"
      shift 2
      ;;
    --gpg-key)
      [[ $# -ge 2 ]] || die "--gpg-key requires a value"
      GPG_KEY="$2"
      shift 2
      ;;
    --no-sign)
      GPG_KEY=""
      shift
      ;;
    --build-source)
      BUILD_SOURCE="true"
      shift
      ;;
    --ppa)
      [[ $# -ge 2 ]] || die "--ppa requires a value"
      PPA_TARGET="$2"
      BUILD_SOURCE="true"
      shift 2
      ;;
    --ppa-dist)
      [[ $# -ge 2 ]] || die "--ppa-dist requires a value"
      PPA_DIST="$2"
      shift 2
      ;;
    --ppa-revision)
      [[ $# -ge 2 ]] || die "--ppa-revision requires a value"
      PPA_REVISION="$2"
      shift 2
      ;;
    --changes)
      [[ $# -ge 2 ]] || die "--changes requires a value"
      CHANGES_FILE="$2"
      CHANGES_FROM_FLAG="true"
      shift 2
      ;;
    --force)
      FORCE="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

if [[ -z "$DEB_PATH" ]]; then
  mapfile -t debs < <(ls -1t "$DEFAULT_RELEASE_DIR"/*.deb 2>/dev/null || true)
  [[ ${#debs[@]} -gt 0 ]] || die "No .deb files found in $DEFAULT_RELEASE_DIR"
  DEB_PATH="${debs[0]}"
fi

[[ -f "$DEB_PATH" ]] || die "Debian package not found: $DEB_PATH"

ensure_packages dpkg-dev apt-utils rsync xz-utils tar python3 python3-pip python3-wheel python3-venv python3-setuptools

command -v dpkg-deb >/dev/null 2>&1 || die "dpkg-deb is required"
command -v dpkg-scanpackages >/dev/null 2>&1 || die "dpkg-scanpackages is required"
command -v apt-ftparchive >/dev/null 2>&1 || die "apt-ftparchive is required"

if [[ -n "$GPG_KEY" ]]; then
  command -v gpg >/dev/null 2>&1 || die "gpg is required for signing"
  if ! gpg --batch --list-secret-keys "$GPG_KEY" >/dev/null 2>&1; then
    die "GPG secret key $GPG_KEY not found; import it or rerun with --no-sign"
  fi
fi

PACKAGE_NAME="$(dpkg-deb -f "$DEB_PATH" Package)"
VERSION="$(dpkg-deb -f "$DEB_PATH" Version)"
ARCH="$(dpkg-deb -f "$DEB_PATH" Architecture)"
[[ -n "$PACKAGE_NAME" && -n "$VERSION" && -n "$ARCH" ]] || die "Unable to read package metadata"

log_info "Preparing apt repo in $REPO_DIR for $PACKAGE_NAME $VERSION ($ARCH)"
mkdir -p "$REPO_DIR"
POOL_DIR="$REPO_DIR/pool/$COMPONENT/${PACKAGE_NAME:0:1}/$PACKAGE_NAME"
mkdir -p "$POOL_DIR"
TARGET_DEB="$POOL_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
cp -f "$DEB_PATH" "$TARGET_DEB"

pushd "$REPO_DIR" >/dev/null
BIN_DIR="dists/$DIST/$COMPONENT/binary-$ARCH"
mkdir -p "$BIN_DIR"
log_info "Generating Packages index"
DPKG_SCANPOUT="$BIN_DIR/Packages"
dpkg-scanpackages "pool/$COMPONENT" >"$DPKG_SCANPOUT"
gzip -kf "$DPKG_SCANPOUT"
xz -kf "$DPKG_SCANPOUT"

log_info "Creating Release metadata"
TMP_CONF="$(mktemp)"
cat >"$TMP_CONF" <<EOF
APT::FTPArchive::Release::Origin "AI-OS";
APT::FTPArchive::Release::Label "AI-OS";
APT::FTPArchive::Release::Suite "$DIST";
APT::FTPArchive::Release::Codename "$DIST";
APT::FTPArchive::Release::Architectures "$ARCH";
APT::FTPArchive::Release::Components "$COMPONENT";
APT::FTPArchive::Release::Description "AI-OS apt repository";
EOF
apt-ftparchive -c "$TMP_CONF" release "dists/$DIST" >"dists/$DIST/Release"
rm -f "$TMP_CONF"

if [[ -n "$GPG_KEY" ]]; then
  log_info "Signing Release files with key $GPG_KEY"
  gpg --batch --yes --local-user "$GPG_KEY" --armor --detach-sign \
    --output "dists/$DIST/Release.gpg" "dists/$DIST/Release"
  gpg --batch --yes --local-user "$GPG_KEY" --armor --clearsign \
    --output "dists/$DIST/InRelease" "dists/$DIST/Release"
fi
popd >/dev/null

if [[ "$BUILD_SOURCE" == "true" ]]; then
  build_source_package "$VERSION" "$PPA_REVISION" "$PPA_DIST"
  sign_changes_file
fi

if [[ -n "$PPA_TARGET" ]]; then
  [[ -n "$CHANGES_FILE" ]] || die "No .changes file available; pass --changes or enable --build-source"
  [[ -f "$CHANGES_FILE" ]] || die "Changes file not found: $CHANGES_FILE"
  ensure_packages dput
  if [[ "$FORCE" == "false" ]]; then
    read -r -p "Upload $CHANGES_FILE to $PPA_TARGET via dput? [y/N] " reply
    case "$reply" in
      [Yy]*) ;;
      *) log_info "Skipping dput upload"; exit 0;;
    esac
  fi
  log_info "Uploading $CHANGES_FILE to $PPA_TARGET"
  dput "$PPA_TARGET" "$CHANGES_FILE"
elif [[ "$CHANGES_FROM_FLAG" == "true" ]]; then
  log_warn "--changes was provided without --ppa; skipping dput upload"
fi

log_info "Repo update complete. Publish $REPO_DIR to your hosting target."
