from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer

from aios.docs.modelcard import generate_modelcard as _mc_generate, scaffold_config as _mc_scaffold
from aios.memory.store import get_db, init_db, list_artifacts

DEFAULT_DREAMS_CONFIG = str((Path.home() / "artifacts" / "dreams" / "config.yaml").as_posix())
DEFAULT_DREAMS_HTML = str((Path.home() / "artifacts" / "dreams" / "model_card.html").as_posix())

modelcard = typer.Typer(help="Generate model cards (uses dreams_mc if available, else fallback)")


@modelcard.command("scaffold-config")
def modelcard_scaffold_config(
    output: str = typer.Option(DEFAULT_DREAMS_CONFIG, "--output", help="Path to write config.yaml"),
    label: Optional[str] = typer.Option(None, "--label", help="Filter training_metrics by label"),
    recent: int = typer.Option(10, "--recent", help="Include up to N recent training_metrics losses"),
):
    conn = get_db()
    init_db(conn)
    try:
        items = list_artifacts(conn, kind="training_metrics", limit=max(50, int(recent)))
        def _match(it: dict) -> bool:
            if label and it.get("label") != label:
                return False
            return True
        picked = [it for it in items if _match(it)][: max(1, int(recent))]
        losses: list[float] = []
        for it in picked:
            try:
                data = it.get("data") or {}
                vals = data.get("losses")
                if isinstance(vals, list):
                    for x in vals[-int(recent):]:
                        try:
                            losses.append(float(x))
                        except Exception:
                            continue
                else:
                    last = data.get("last_loss")
                    if last is not None:
                        try:
                            losses.append(float(last))
                        except Exception:
                            pass
            except Exception:
                continue
    finally:
        conn.close()
    out_dir = Path(output).expanduser()
    img_dir = out_dir.parent / "images"
    img_dir.mkdir(parents=True, exist_ok=True)
    _PNG_1x1 = (
        b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\x0cIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82"
    )
    def _write_png(path: Path) -> str:
        try:
            with open(path, "wb") as f:
                f.write(_PNG_1x1)
        except Exception:
            pass
        return str(path)
    logo_path = str(Path(_write_png(img_dir / "logo.png")).resolve())
    data_figpath = str(Path(_write_png(img_dir / "data.png")).resolve())
    result_table_figpath = str(Path(_write_png(img_dir / "result_table.png")).resolve())
    cm_figpath = str(Path(_write_png(img_dir / "cm.png")).resolve())
    acc_figpath = str(Path(_write_png(img_dir / "acc.png")).resolve())
    loss_figpath = str(Path(_write_png(img_dir / "loss.png")).resolve())
    uncertainty_figpath = str(Path(_write_png(img_dir / "uncertainty.png")).resolve())
    last_loss = float(losses[-1]) if losses else None
    describe_overview = (
        "Auto-generated model card. "
        + (f"Ingested {len(losses)} loss points; last_loss={last_loss:.4f}." if last_loss is not None else "No training metrics found yet.")
    )
    cfg = {
        "logo_path": logo_path,
        "data_figpath": data_figpath,
        "result_table_figpath": result_table_figpath,
        "cm_figpath": cm_figpath,
        "acc_figpath": acc_figpath,
        "loss_figpath": loss_figpath,
        "uncertainty_figpath": uncertainty_figpath,
        "describe_overview": describe_overview,
        "dataset_name": "synthetic/toy",
        "num_target_class": 5,
        "ground_truth": "n/a",
        "split_ratio": "80/20",
        "preprocess_steps": "none",
        "describe_dataset": "Tiny synthetic samples generated by AI-OS training loop.",
        "model_output": ["action id (0-4)", "reward estimate"],
        "model_input": ["state vector (toy)"],
        "learning_approach": "reinforcement learning (toy)",
        "model_type": "MLP/Tabular (toy)",
        "learning_rate": "n/a",
        "batch_size": 32,
        "additional_info": "Auto-generated by AI-OS vendor-dreams scaffold-config.",
        "model_details": "Simple proof-of-concept training loop; replace with your model details.",
        "performance_comments": (
            f"Last observed loss: {last_loss:.4f}. Lower is better in this toy setup." if last_loss is not None else "Performance metrics not available yet."
        ),
        "limitation_details": [
            "Toy environment; metrics do not reflect real-world performance.",
            "No validation/test split rigor.",
            "Small synthetic dataset and trivial model."
        ],
        "uncertainty_describe": "Uncertainty estimation not computed (placeholder).",
        "references": "https://github.com/Wulfic/AI-OS",
    }
    cfg["_aios_metrics"] = {"losses": [float(x) for x in losses[-recent:]], "count": int(len(losses))}
    p = Path(output)
    p.parent.mkdir(parents=True, exist_ok=True)
    ok, details = _mc_scaffold(cfg, output=str(p))
    print({"ok": ok, **details})


@modelcard.command("generate")
def modelcard_generate(
    config: str = typer.Option(DEFAULT_DREAMS_CONFIG, "--config", help="Path to config.yaml (from scaffold-config)"),
    output: str = typer.Option(DEFAULT_DREAMS_HTML, "--output", help="Output HTML path"),
    version: str = typer.Option("1.0", "--version", help="Model card specification version"),
):
    ok, details = _mc_generate(config, output, version)
    print({"ok": ok, **details})


def register(app: typer.Typer) -> None:
    app.add_typer(modelcard, name="modelcard")
